In [15]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.add(mat1,mat2)
print(sumMat)

[[ 3  5  8]
 [ 9 11 13]
 [15 17 10]]


In [16]:
#2. Write a Python Program to Multiply Two Matrices?
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

mulMat = np.dot(mat1,mat2)
print(mulMat)

[[ 44  51  22]
 [ 81  96  57]
 [126 150  93]]


In [3]:
#3. Write a Python Program to Transpose a Matrix?

#Unable to solve

In [10]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
str = input("Enter some string :")

words = str.split()
words.sort()
for word in words:
    print(word)

Enter some string :cts kolkata in sector five
cts
five
in
kolkata
sector


In [23]:
#5. Write a Python Program to Remove Punctuation From a String?
import string

string_char = string.punctuation

s=input("Enter string : ")

for i in s:
    #print(i)
    if i in string_char:
        s=s.replace(i,"")
        
print(s)

Enter string : al@hb#6yu!co
alhb6yuco
